// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/31/2025, 5:43:25 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marquisabah/Documents/icCare/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/icCare/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/icCare/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/icCare/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/icCare/plugins/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/icCare/composables/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/icCare/utils/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/icCare/pages/index.vue","/Users/marquisabah/Documents/icCare/pages/profile.vue","/Users/marquisabah/Documents/icCare/pages/auth/login.vue","/Users/marquisabah/Documents/icCare/pages/auth/signup.vue","/Users/marquisabah/Documents/icCare/pages/reports/rep.vue","/Users/marquisabah/Documents/icCare/pages/activity-log.vue","/Users/marquisabah/Documents/icCare/pages/notification.vue","/Users/marquisabah/Documents/icCare/pages/reports/index.vue","/Users/marquisabah/Documents/icCare/pages/auth/verify-otp.vue","/Users/marquisabah/Documents/icCare/pages/dashboard/index.vue","/Users/marquisabah/Documents/icCare/pages/attributes/index.vue","/Users/marquisabah/Documents/icCare/pages/biospecimen/tracking.vue","/Users/marquisabah/Documents/icCare/pages/biospecimen/attributes.vue","/Users/marquisabah/Documents/icCare/pages/biospecimen/bulk-upload.vue","/Users/marquisabah/Documents/icCare/pages/biospecimen/registration.vue","/Users/marquisabah/Documents/icCare/pages/user-management/manage-role.vue","/Users/marquisabah/Documents/icCare/pages/user-management/manage-user.vue","/Users/marquisabah/Documents/icCare/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/icCare/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/icCare/app.config.{js,ts,mjs}","/Users/marquisabah/Documents/icCare/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;